### ISSUE TITLE
A couple of bugs and/or missing code while running for UCR on TS2Vec: hierarchical_contrastive_loss_soft not defined

### ISSUE THREAD

**Issue by shivam-grover** [seunghan96/softclt#1]
Hi authors,
Thank you for this repository. I am trying to run training on a single UCR dataset using the commands in the scripts/ucr.sh file.

The issue I am facing right now is a missing hierarchical_contrastive_loss_soft method.
I get this error stack:
python3 -u train.py ItalyPowerDemand --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
Dataset: ItalyPowerDemand
Arguments: Namespace(alpha=0.5, batch_size=8, dataset='ItalyPowerDemand', dist_type='DTW', epochs=None, eval=True, expid=2, gpu=0, irregular=0, iters=None, lambda_=0.5, loader='UCR', lr=0.001, max_threads=8, max_train_length=3000, repr_dims=320, save_every=None, seed=42, separate_reg=False, tau_inst=0, tau_temp=0)
Loading data... Saving & Loading DTW ...
Preprocessing UTS ...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 67/67 [00:00<00:00, 93.13it/s]
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    loss_log = model.fit(
  File "/home/shivam/Desktop/Experiments/softclt-main/softclt_ts2vec/soft_ts2vec.py", line 134, in fit
    loss = hierarchical_contrastive_loss_soft(
NameError: name 'hierarchical_contrastive_loss_soft' is not defined

Could you tell me what library this method is coming from, as i could not find it online. Or if you had written it yourself, could you add the code for this method.

There were a few other issues as well that I had to solve before reaching here. I'll mention them here in case one of them caused some issue:
1. I had to add the line below to train.py
    `parser.add_argument('--max-threads', type=int, default=None, help='The maximum allowed number of threads used by this process')`

2. I had to install tslearn==0.5.2.3 as the latest one was not compatible with ts2vec's original requirements.
3. In save_sim_mat, the first line references dist_mat which is not one of the parameters, hence the reference before assignment error. So I had to move after the else block.

**Comment by seunghan96** [comment]
Sorry for the late reply. By now, all the bugs you mentioned should be fixed!
